### ISSUE TITLE
Panic in parse_ipv6_literal()

### ISSUE THREAD

**Issue by eikendev** [timothee-haudebourg/iref#16]
Hi everyone,

Using `iref = "2.2.3"`, I noticed a panic in `parse_ipv6_literal()` with very simple input to `IriBuf::new()`:

```rust
use iref::IriBuf;

fn main() {
    let _ = IriBuf::new("https://[1.1.1.1");
}
```

See below for details on the panic resulting from running the code above. I think instead of a panic, this should throw an error.

The sourrounding code is quite difficult to read, but maybe with some guidance we can tackle this issue together. Overall, the panic indicates a failing assertion, so a starting point may be to validate its assumption.

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/ireftest`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `128`,
 right: `32`', <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/parsing/mod.rs:591:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/50d3ba5bcbf5c7e13d4ce068d3339710701dd603/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/50d3ba5bcbf5c7e13d4ce068d3339710701dd603/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/50d3ba5bcbf5c7e13d4ce068d3339710701dd603/library/core/src/panicking.rs:211:5
   4: iref::parsing::parse_ipv6_literal
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/parsing/mod.rs:591:10
   5: iref::parsing::parse_ip_literal
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/parsing/mod.rs:670:25
   6: iref::parsing::parse_host
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/parsing/mod.rs:720:21
   7: iref::parsing::parse_authority
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/parsing/mod.rs:755:17
   8: iref::parsing::ParsedIriRef::new
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/parsing/mod.rs:101:24
   9: iref::reference::buffer::IriRefBuf::new
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/reference/buffer.rs:56:7
  10: iref::iri::buffer::IriBuf::new
             at <redacted>/.config/cargo/registry/src/github.com-1ecc6299db9ec823/iref-2.2.3/src/iri/buffer.rs:24:17
  11: ireftest::main
             at ./src/main.rs:4:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/50d3ba5bcbf5c7e13d4ce068d3339710701dd603/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by timothee-haudebourg** [comment]
Hi @eikendev, thanks for the report. You are right, this should not panic but return an error.
